# Generated by Django 2.0.7 on 2024-08-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
